version: '3'

services:
  cryptowaffle:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    restart: unless-stopped
    container_name: cryptowaffle_site
    env_file:
      - .env 